// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	CountCategory(ctx context.Context, id int32) (int64, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetProduct(ctx context.Context, id int32) (GetProductRow, error)
	ListCategory(ctx context.Context) ([]Category, error)
	ListProduct(ctx context.Context) ([]ListProductRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
